# deploy.yml
name: deploy to huaweiyun
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 读取仓库内容
      - name: Checkout
        uses: actions/checkout@v4
      # 使用 node:20
      - name: use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      # npm install
      - name: npm install and build
        run: |
          npm install
          npm i -D @vuepress/bundler-vite@next
          # 安装 vuepress
          npm i -D vuepress@next
          # 安装 主题和打包工具
          npm i -D vuepress-theme-plume @vuepress/bundler-vite@next
          npm run docs:build
        env:
          CI: true
      - name: 部署到服务器
        uses: easingthemes/ssh-deploy@v2.1.1
        with:
              SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
              ## 复制操作的参数。"-avzr --delete"意味部署时清空服务器目标目录下的文件
              ARGS: "-rlgoDzvc -i --delete"
              SOURCE: "dist/"
              REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
              REMOTE_USER: ${{ secrets.REMOTE_USER }}
              TARGET: ${{ secrets.TARGET }}
              EXCLUDE: "/dist/, /node_modules/"
