name: docs

on:
  # 监听 master 分支上的 push 事件
  push:
    branches: [master]
  # trigger deployment manually
  workflow_dispatch:

jobs:
  build_job:
    runs-on: ubuntu-latest   #运行环境
    name: build
    steps:
      - name: 签出到虚拟机
        uses: actions/checkout@v4  #签到虚拟机上
      - name: 安装nodejs-v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: 构建 VuePress site
        run: |
          npm i -D vuepress@next
          npm i -D vuepress-theme-plume @vuepress/bundler-vite@next
          npm run docs:build
      - name: 部署到服务器
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'root'   #ssh user name
          server: '${{ secrets.REMOTE_HOST }}' #引用之前创建好的secret
          ssh_private_key: ${{ secrets.ACCESS_TOKEN }} #引用之前创建好的secret
          local_path: '.dist/'  # 对应我们项目build的文件夹路径
          remote_path: '/home/uiiiii'
#
#