# deploy.yml
name: deploy to huaweiyun
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 读取仓库内容
      - name: Checkout
        uses: actions/checkout@v4
      # 使用 node:20
      - name: use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      # npm install
      - name: npm install and build
        run: |
          npm install
          npm run docs:build
        env:
          CI: true
      - name: vuepress-deploy
        uses: easingthemes/ssh-deploy@v5.0.0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
          ARGS: "-avz --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}
