name: docs

on:
  # 监听 master 分支上的 push 事件
  push:
    branches: [master]
  # trigger deployment manually
  workflow_dispatch:

jobs:
  build_job:
    runs-on: ubuntu-latest   #运行环境
    name: build
    steps:
      - name: 签出到虚拟机
        uses: actions/checkout@v4  #签到虚拟机上
      - name: 安装nodejs-v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: 构建 VuePress site
        run: |
          npm i -D vuepress@next
          npm i -D vuepress-theme-plume @vuepress/bundler-vite@next
          npm run docs:build
      - name: 部署到服务器
        uses: easingthemes/ssh-deploy@latest  # 使用最新的ssh-deploy action
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}  # 在GitHub仓库的Secrets中设置的SSH私钥
          ARGS: '-avzr --delete'
          SOURCE: 'dist/'  # VuePress 2构建输出的目录
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}  # 云主机的IP地址或域名
          REMOTE_USER: ${{ secrets.REMOTE_USER }}  # 云主机的用户名
          TARGET: ${{ secrets.TARGET }}  # 云主机上存放VuePress 2站点的目录

#
# with:
#              SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
#              ## 复制操作的参数。"-avzr --delete"意味部署时清空服务器目标目录下的文件
#              ARGS: "-rlgoDzvc -i --delete"
#              SOURCE: "dist/"
#              REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
#              REMOTE_USER: ${{ secrets.REMOTE_USER }}
#              TARGET: ${{ secrets.TARGET }}
#              EXCLUDE: "/dist/, /node_modules/"