name: docs

on:
  # 监听 master 分支上的 push 事件
  push:
    branches: [master]
  # trigger deployment manually
  workflow_dispatch:
# jobs: 将工作流运行的所有作业组合到一起。
jobs:
  build_job:
    runs-on: ubuntu-latest   #运行环境
    name: build
    # steps: 将作业中运行的所有步骤组合在一起。
    steps:
      - name: 签出到虚拟机
        uses: actions/checkout@v4  #签到虚拟机上    uses: 指定需要运行的 action。

      - name: 安装nodejs-v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: 安装依赖
        run: npm install
      
      - name: 构建VuePress site
        run: npm run docs:build

      - name: 部署到服务器
        uses: easingthemes/ssh-deploy@v2.0.7  # 使用最新的ssh-deploy action
        # env: 指定运行 action 时需要用到的环境变量的值。
        # 变量在github项目的settings--secrets and variables--actions--repository secrets--
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}  # 在GitHub仓库的Secrets中设置的SSH私钥   创建ssh密钥时不要设置密码，具体看此actions仓库地址
          ARGS: '-avzr --delete'
          SOURCE: './docs/.vuepress/dist/'  # 源目录，相对于$GITHUB_WORKSPACE根目录的路径
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}  # 云主机的IP地址或域名
          REMOTE_USER: ${{ secrets.REMOTE_USER }}  # 云主机的用户名
          TARGET: ${{ secrets.TARGET }}  # 云主机上存放VuePress 2站点的目录